{
 "title": "System monitorowania Raspberry Pi",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Docker - grupa [cadvisor]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wykorzystanie CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_working_set_bytes{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ruch nadawany",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ruch odbierany",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aktywność dysku (operacje odczytu)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_fs_reads_bytes_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aktywność dysku (operacje zapisu)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_fs_writes_bytes_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aplikacja Python - grupa [app]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tempo przychodzących zapytań [R]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 666 },
     "targets": [
      {
       "expr": "rate(app_requests_total[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tempo błędów aplikacji [E]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1075 },
     "targets": [
      {
       "expr": "rate(app_errors_total[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Czas odpowiedzi aplikacji [D]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1083 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(app_request_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Serwer Prometheus - grupa [prometheus]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Liczba stworzonych serii czasowych",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Liczba monitorowanych instancji",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 1)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Liczba bloków serii czasowych w bazie danych",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Czas odpowiedzi na zapytania (kwantyl q=0.99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"0.99\", slice=\"inner_eval\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci RAM przez proces serwera Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "Pamięć fizyczna"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "Pamięć wirtualna (fizyczna + zaalokowana wirtualna)"
    }
   ]
  },
  {
   "title": "Liczba zapisywanych wartości metryk do bazy danych serii czasowej",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Czas trwania pobierania wartości metryk z podziałem na grupy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba pobieranych wartości metryk z podziałem na grupy monitorowania",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (job) (scrape_samples_scraped)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Raspberry Pi - grupa [rpi]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Wykorzystanie CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{job=\"rpi\",mode!=\"idle\"}[$__rate_interval])) / sum by (instance) (irate(node_cpu_seconds_total{job=\"rpi\"}[$__rate_interval]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"rpi\"} - (node_memory_MemAvailable_bytes{job=\"rpi\"})) / node_memory_MemTotal_bytes{job=\"rpi\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci SWAP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"rpi\"} - node_memory_SwapFree_bytes{job=\"rpi\"}) / node_memory_SwapTotal_bytes{job=\"rpi\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci dyskowej",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{job=\"rpi\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"rpi\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"rpi\", mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatura CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"rpi\", type=\"cpu-thermal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pojemność pamięci dyskowej",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"rpi\", mountpoint=\"/\", fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Czas działania urządzenia",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"rpi\"} - node_boot_time_seconds{job=\"rpi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liczba rdzeni CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (cpu) (node_cpu_seconds_total{job=\"rpi\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Całkowita pojemność pamięci RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"rpi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pojemność pamięci SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"rpi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"rpi\", mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba zadań w kolejce CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by (instance) (node_load1{job=\"rpi\"}) / count by (instance) (node_cpu_seconds_total{job=\"rpi\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"rpi\"} - (node_memory_MemAvailable_bytes{job=\"rpi\"})) / node_memory_MemTotal_bytes{job=\"rpi\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci SWAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"rpi\"} - node_memory_SwapFree_bytes{job=\"rpi\"}) / node_memory_SwapTotal_bytes{job=\"rpi\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Całkowity ruch sieciowy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"rpi\", device=\"eth0.10\"}[$__rate_interval]) * 8",
     "legendFormat": "Ruch nadawany"
    },
    {
     "expr": "-irate(node_network_receive_bytes_total{job=\"rpi\", device=\"eth0.10\"}[$__rate_interval]) * 8",
     "legendFormat": "Ruch odbierany"
    }
   ]
  },
  {
   "title": "Liczba odrzuconych pakietów",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "targets": [
    {
     "expr": "(rate(node_network_receive_drop_total{job=\"rpi\", device=\"eth0.10\"}[$__rate_interval]) + rate(node_network_transmit_drop_total{job=\"rpi\", device=\"eth0.10\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba pakietów z błędami",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "expr": "(rate(node_network_receive_errs_total{job=\"rpi\", device=\"eth0.10\"}[$__rate_interval]) + rate(node_network_transmit_errs_total{job=\"rpi\", device=\"eth0.10\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wykorzystanie dysku (aktywność wejścia/wyjścia)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{job=\"rpi\"}[$__rate_interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba operacji wejścia/wyjścia oczekujących w kolejce",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_weighted_seconds_total{job=\"rpi\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatura CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"rpi\", type=\"cpu-thermal\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maszyny wirtualne - grupa [node]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 }
  },
  {
   "title": "Wykorzystanie CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba zadań w kolejce CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum by (instance) (node_load1{job=\"node\"}) / count by (instance) (node_cpu_seconds_total{job=\"node\", mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"node\"} - (node_memory_MemAvailable_bytes{job=\"node\"})) / node_memory_MemTotal_bytes{job=\"node\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci SWAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"node\"} - node_memory_SwapFree_bytes{job=\"node\"}) / node_memory_SwapTotal_bytes{job=\"node\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Całkowita przepływność interfejsu sieciowego",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{job=\"node\", device=\"enp0s3\"}[$__rate_interval]) + irate(node_network_transmit_bytes_total{job=\"node\", device=\"enp0s3\"}[$__rate_interval])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba odrzuconych pakietów",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 118 },
   "targets": [
    {
     "expr": "(rate(node_network_receive_drop_total{job=\"node\", device=\"enp0s3\"}[$__rate_interval]) + rate(node_network_transmit_drop_total{job=\"node\", device=\"enp0s3\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba pakietów z błędami",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 118 },
   "targets": [
    {
     "expr": "(rate(node_network_receive_errs_total{job=\"node\", device=\"enp0s3\"}[$__rate_interval]) + rate(node_network_transmit_errs_total{job=\"node\", device=\"enp0s3\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wykorzystanie dysku (aktywność wejścia/wyjścia)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{job=\"node\"}[$__rate_interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liczba operacji wejścia/wyjścia oczekujących w kolejce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_weighted_seconds_total{job=\"node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wykorzystanie pamięci dysku",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}