global:
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'alertmanager@example.com'
  smtp_require_tls: false

route:
  group_by: ['source']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: operations_team
  routes:
  - match:
      source: app
    receiver: application_team
    continue: true
  - match:
      source: app
    receiver: operations_team
  - match_re:
      source: ^(node|rpi)$
    receiver: operations_team

receivers:
  - name: 'application_team'
    email_configs:
      - to: 'application-team@example.com'
  - name: 'operations_team'
    email_configs:
      - to: 'operations-team@example.com'
