global:
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'alertmanager@example.com'
  smtp_require_tls: false

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'test@example.com'
