groups:
  - name: app_alerts
    rules:
      - alert: AppUnavailable
        expr: up{job="app"} == 0
        for: 1m
        labels:
          severity: critical
          source: app
        annotations:
          summary: Application on node {{ $labels.instance }} is unavailable!
      - alert: HighErrorRate
        expr: app:errors:rate > 0.2
        for: 1m
        labels:
          severity: warning
          source: app
        annotations:
          summary: Application on node {{ $labels.instance }} had high error rate for 5 minutes.
      - alert: LongResponseTime
        expr: app:response_time:rate_quantile09 > 1
        for: 1m
        labels:
          severity: warning
          source: app
        annotations:
          summary: Application on node {{ $labels.instance }} had long response time for 5 minutes.