groups:
  - name: node_alerts
    rules:
      - alert: NodeUnavailable
        expr: up{job="node"} == 0
        for: 5m
        labels:
          severity: critical
          source: node
        annotations:
          summary: Node {{ $labels.instance }} is unavailable!
      - alert: HighNodeCPUUsage
        expr: node:cpu_usage:percentage > 80
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had high CPU usage for 10 minutes.
      - alert: HighNodeCPUSaturation
        expr: node:cpu_saturation:tasks > 2
        for: 5m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had high CPU saturation for 5 minutes.
      - alert: HighNodeRAM
        expr: node:memory_usage:percentage > 80
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had high RAM usage for 10 minutes.
      - alert: HighNodeSWAPUsage
        expr: node:swap_usage:percentage > 20
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had high SWAP usage for 10 minutes.
      - alert: NetworkInterfaceMaxThroughput
        expr: node:network_throughput:bits_sec > 9500000000 # Dla interfejsu o przepustowości 1 Gb/s
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} was at almost max interface throughput for 10 minutes.
      - alert: HighNodePacketDropped
        expr: node:network_packets_dropped:rate > 10
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had a significant number of dropped packets for 10 minutes.    
      - alert: HighNodePacketError
        expr: node:network_packets_errors:rate > 10
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had a significant number of packets with errors for 10 minutes.  
      - alert: HighNodeDiskUsage
        expr: node:disk_usage:percentage > 90
        for: 5m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had high disk usage for 5 minutes.       
      - alert: HighNodeDiskSaturation
        expr: node:disk_saturation:tasks > 5
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} had high disk saturation for 10 minutes.    
      - alert: HighNodeDiskSpaceUsed
        expr: node:filesystem_usage:percentage > 90
        for: 10m
        labels:
          severity: warning
          source: node
        annotations:
          summary: Node {{ $labels.instance }} has 90% of disk space used.
      - alert: NodeDiskWillFillIn8Hours
        expr: predict_linear(node_filesystem_free_bytes{job="node", mountpoint="/"}[1h], 8*3600) < 0
        for: 10m
        labels:
          severity: critical
          source: node
        annotations:
          summary: Disk on node {{ $labels.instance }} will fill in 8 hours.