groups:
  - name: rpi_docker_rules
    rules:
      - record: rpi_docker:cpu_usage:percentage 
        expr: sum by (name) (irate(container_cpu_usage_seconds_total{job="cadvisor", name=~".+"}[5m])) * 100
      - record: rpi_docker:ram_usage:bytes
        expr: sum by (name) (container_memory_usage_bytes{job="cadvisor", name=~".+"})