groups:
  - name: rpi_docker_alerts
    rules:
      - alert: ContainerUnavailable
        expr: time() - last_over_time(container_last_seen{name=~".+"}[5m]) > 60
        for: 1m
        labels:
          severity: critical
          source: rpi
        annotations:
          summary: Container {{ $labels.name }} is unavailable!
      - alert: HighContainerCpuUsage
        expr: rpi_docker:cpu_usage:percentage > 70
        for: 10m
        labels:
          severity: critical
          source: rpi
        annotations:
          summary: Container {{ $labels.name }} had high CPU usage for 10 minutes!
      - alert: HighContainerRamUsage
        expr: rpi_docker:ram_usage:bytes > 0.2 * node_memory_MemTotal_bytes{job="rpi"}
        for: 10m
        labels:
          severity: critical
          source: rpi
        annotations:
          summary: Container {{ $labels.name }} had high RAM usage for 10 minutes!