groups:
  - name: rpi_docker_alerts
    rules:
      - alert: ContainerUnavailable
        expr: time() - last_over_time(container_last_seen{name=~".+"}[5m]) > 60
        for: 0m
        labels:
          severity: critical
          source: rpi
        annotations:
          summary: Container {{ $labels.name }} is unavailable!