groups:
  - name: rpi_rules
    rules:
      - record: rpi:cpu_usage:percentage 
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="rpi", mode="idle"}[5m])) * 100)
      - record: rpi:cpu_saturation:tasks
        expr: sum by (instance) (node_load1{job="rpi"}) / count by (instance) (node_cpu_seconds_total{job="rpi", mode="idle"})
      - record: rpi:memory_usage:percentage
        expr: ((node_memory_MemTotal_bytes{job="rpi"} - (node_memory_MemAvailable_bytes{job="rpi"})) / node_memory_MemTotal_bytes{job="rpi"}) * 100
      - record: rpi:swap_usage:percentage
        expr: ((node_memory_SwapTotal_bytes{job="rpi"} - node_memory_SwapFree_bytes{job="rpi"}) / node_memory_SwapTotal_bytes{job="rpi"}) * 100
      - record: rpi:network_throughput:bits_sec
        expr: sum by (instance) (irate(node_network_receive_bytes_total{job="rpi", device="eth0.10"}[5m]) + irate(node_network_transmit_bytes_total{job="rpi", device="eth0.10"}[5m])) * 8
      - record: rpi:network_packets_dropped:rate
        expr: (rate(node_network_receive_drop_total{job="rpi", device="eth0.10"}[5m]) + rate(node_network_transmit_drop_total{job="rpi", device="eth0.10"}[5m]))
      - record: rpi:network_packets_errors:rate
        expr: (rate(node_network_receive_errs_total{job="rpi", device="eth0.10"}[5m]) + rate(node_network_transmit_errs_total{job="rpi", device="eth0.10"}[5m]))
      - record: rpi:disk_usage:percentage
        expr: sum by (instance) (rate(node_disk_io_time_seconds_total{job="rpi"}[5m])) * 100
      - record: rpi:disk_saturation:tasks
        expr: sum by (instance) (rate(node_disk_io_time_weighted_seconds_total{job="rpi"}[5m]))
      - record: rpi:filesystem_usage:percentage
        expr: (node_filesystem_size_bytes{job="rpi", mountpoint="/"} - node_filesystem_free_bytes{job="rpi", mountpoint="/"}) / node_filesystem_size_bytes{job="rpi", mountpoint="/"} * 100
      - record: rpi:dropped_packets:rate
        expr: (rate(node_network_receive_drop_total{job="rpi", device="eth0.10"}[5m]) + rate(node_network_transmit_drop_total{job="rpi", device="eth0.10"}[5m]))
      - record: rpi:temperature:no_op
        expr: node_thermal_zone_temp{job="rpi", type="cpu-thermal"}