- name: Wdrożenie systemu monitorowania na Raspbrry Pi
  hosts: virtual_servers
  tasks:
    - name: Kopiowanie katalogu na Raspberry Pi
      ansible.builtin.copy:
        src: ./compose.yml
        dest: /home/{{ ansible_user }}/docker/cadvisor/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    - name: Użycie Docker Compose w celu uruchomienia systemu monitorowania
      command: docker compose up -d
      args:
        chdir: /home/{{ ansible_user }}/docker/cadvisor/