global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
    - "rules/*_rules.yml"
    - "rules/*_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rpi'
    static_configs:
      - targets: ['192.168.10.10:9100']
        
  - job_name: 'node'
    file_sd_configs:
      - files:
        - 'targets/nodes.json'
        refresh_interval: 5m

  - job_name: 'app'
    file_sd_configs:
      - files:
        - 'targets/app.json'
        refresh_interval: 5m

  - job_name: 'exporter'
    file_sd_configs:
      - files:
        - 'targets/exporter.json'
        refresh_interval: 5m

  # - job_name: 'scaling'
  #   file_sd_configs:
  #     - files:
  #       - 'targets/scaling.json'
  #       refresh_interval: 5m