global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
    - "rules/*_rules.yml"
    - "rules/*_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.10.21:9100','192.168.10.22:9100','192.168.10.23:9100']

  - job_name: 'rpi'
    static_configs:
      - targets: ['192.168.10.10:9100']
        #- job_name: 'docker'
        #static_configs:
        #- targets: ['192.168.10.21:8080','192.168.10.22:8080','192.168.10.23:8080']
