- name: Wdrożenie testowej aplikacji internetowej
  hosts: virtual_servers
  tasks:
    - name: Zatrzymanie kontenera jeżeli istnieje
      command: docker compose down
      args:
        chdir: /home/{{ ansible_user }}/app/
      ignore_errors: true

    - name: Kopiowanie katalogu z kodem aplikacji
      ansible.builtin.copy:
        src: ../testing/app/
        dest: /home/{{ ansible_user }}/app/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Budowanie i uruchomienie kontenera za pomocą Docker Compose
      ansible.builtin.command:
        cmd: docker compose up --build -d
      args:
        chdir: /home/{{ ansible_user }}/app/

    - name: Usunięcie starych obrazów kontenerów
      command: docker image prune -af