- name: Wdrożenie drugiej wersji własnego eksportera do testowania wydajności
  hosts: virtual_servers
  tasks:
    - name: Zatrzymanie kontenera jeżeli istnieje
      command: docker compose down
      args:
        chdir: /home/{{ ansible_user }}/testing/exporter_v2/
      ignore_errors: true

    - name: Kopiowanie katalogu z kodem eksportera
      ansible.builtin.copy:
        src: ../testing/exporter_v2/
        dest: /home/{{ ansible_user }}/testing/exporter_v2/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Budowanie i uruchomienie kontenera za pomocą Docker Compose
      ansible.builtin.command:
        cmd: docker compose up --build -d
      args:
        chdir: /home/{{ ansible_user }}/testing/exporter_v2/

    - name: Usunięcie starych obrazów kontenerów
      command: docker image prune -af